require './lib/board'
require 'rspec'
require 'pry'

RSpec.describe Board do

  it "creates board" do
    game = Board.new
    expect{game.print_board}.to output(
      <<~EXPECTED
      .......
      .......
      .......
      .......
      .......
      .......
       EXPECTED
    ).to_stdout
  end

  xit "test the move" do
    # game = Board.new
    expect{game.move(A)}.to output(
      <<~EXPECTED
      .......
      .......
      .......
      .......
      .......
      x......
       EXPECTED
      ).to_stdout
  end


end
